server:
  port: 8080
  servlet:
    context-path: /
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/stuscoretest?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Nczx2020
    jackson:
      date-format: yyyy-MM-dd HH:mm:ss
      time-zone: GMT+8
# MyBatis
mybatis:
  # 搜索指定包别名
  #typeAliasesPackage: com.bahetcoder.**.dao
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
#  mapperLocations: classpath*:mapper/**/*Mapper.xml
  mapper-locations: classpath:mapper/**/*.xml

tomcat:
  # tomcat的URI编码
  uri-encoding: UTF-8
  # tomcat最大线程数，默认为200
  max-threads: 800
  # Tomcat启动初始化的线程数，默认值25
  min-spare-threads: 30

# 日志配置
logging:
  level:
    com.bahetcoder: debug
    org.springframework: warn